"""
Supplementary Table T6 — per-cell patch-seq annotations behind Figure 4d-f.

Every other input to Figure 4 is public (Bigdeli, SEA-AD, Siletti, Lee/Dalley,
DANDI). The scANVI supertype calls are not: they come from an iterative mapping
of the Allen Institute's human patch-seq collection onto the SEA-AD taxonomy,
generated by the SEA-AD group and provided by Kyle Travaglini, and were never
part of the formal SEA-AD data release. Depositing the 150 rows this figure
actually uses closes that gap without redistributing the full 4,549-cell file.

Columns are the identifiers needed to rejoin the public data, the labels that
cannot be recovered from it, and the two released intrinsic features the figure
consumes. `tau_ms` is stated in milliseconds; the upstream release stores tau in
seconds, which is an easy trap to fall into when rejoining.
"""
import pandas as pd

import os as _os

# Repo-relative, so the chain runs from any clone. External data that is not in
# the repo is still resolved by absolute path or an environment override below.
GEN = _os.path.dirname(_os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))
PAPER = _os.path.dirname(GEN)

UP = _os.environ.get("PATCHSEQ_REPO",
                     _os.path.expanduser("~/Github/human_int_patch_seq"))

OUT = f"{GEN}/results/tables/supp_T6_patchseq_sst_annotations.csv"

# the five reconstructions shown in panels e/f, depth-ordered
EXEMPLARS = {1079568285: "Sst_20", 819770858: "Sst_25", 1037461069: "Sst_3",
             758996755: "Sst_5", 797048104: "Sst_1"}

cells = pd.read_csv(f"{UP}/data/patchseq/patchseq_combined.csv", low_memory=False)
sst = cells[(cells.subclass_scANVI == "Sst") & cells.cortical_layer.notna()].copy()

sst["tau_ms"] = sst.tau * 1000.0
sst["figure_exemplar"] = sst.specimen_id.isin(EXEMPLARS)
out = sst[[
    "specimen_id", "donor", "brain_region", "cortical_layer",
    "subclass_scANVI", "subclass_conf_scANVI",
    "supertype_scANVI", "supertype_conf_scANVI",
    "sag", "tau_ms", "figure_exemplar",
]].sort_values(["supertype_scANVI", "specimen_id"]).reset_index(drop=True)
out.to_csv(OUT, index=False)

assert len(out) == 150 and out.figure_exemplar.sum() == 5
for sid, st in EXEMPLARS.items():
    got = out.loc[out.specimen_id == sid, "supertype_scANVI"].iloc[0]
    assert got == st, f"{sid}: expected {st}, got {got}"

print(f"{len(out)} cells | {out.donor.nunique()} donors | "
      f"{out.supertype_scANVI.nunique()} supertypes | "
      f"{out.brain_region.nunique()} regions | {int(out.sag.notna().sum())} with sag")
print(f"wrote {OUT}")
