#!/usr/bin/env python3
"""
Build the data tables for the cell-typing validation supplement.

Single, symmetric recipe for all four panels so the subclass/supertype
proportion panels and the subclass/supertype depth panels are directly
comparable (the committed CSVs were generated by different scripts with
different donor sets / cortical gates -- this script replaces that).

Recipe (both platforms, cortical L1-L6 only, correlation-classifier labels):
  - Xenium  : all 24 donors, corr_qc_pass cells in cortical layers
              (config.load_cells(cortical_only=True, qc_mode='corr')),
              labels corr_subclass / corr_supertype.
  - MERFISH : SEA-AD manually depth-annotated cortical cells, 27 donors
              (config.load_merfish_cortical()), labels Subclass / Supertype.
  - Proportions : per-donor composition, then MEAN across donors
                  (donor-averaged so large sections don't dominate).
  - Depth       : pooled-cell MEDIAN normalized depth per cell type
                  (Xenium = predicted_norm_depth, MERFISH = manual depth).
  - A cell type enters a panel only if it has >= MIN_CELLS on BOTH platforms.

Outputs (output/celltyping_supplement/data/):
  prop_subclass.csv, prop_supertype.csv, depth_subclass.csv, depth_supertype.csv
  concordance_stats.csv  (Pearson raw, Pearson log10, Spearman, n per panel)
"""
import os
import sys
import numpy as np
import pandas as pd
from scipy.stats import pearsonr, spearmanr

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import (
    H5AD_DIR, EXCLUDE_SAMPLES, HAS_MERFISH_REF,
    SUBCLASS_TO_CLASS, load_cells, load_merfish_cortical,
)

MIN_CELLS = 20  # per-platform minimum to report a cell type
OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       "..", "..", "output", "celltyping_supplement", "data")
OUT_DIR = os.path.abspath(OUT_DIR)
os.makedirs(OUT_DIR, exist_ok=True)


def mean_prop_across_donors(df, donor_col, label_col):
    """Per-donor proportions, then mean across donors. Returns Series indexed by celltype."""
    recs = []
    for donor, grp in df.groupby(donor_col, observed=True):
        total = len(grp)
        if total == 0:
            continue
        vc = grp[label_col].value_counts()
        for ct, n in vc.items():
            recs.append({"celltype": str(ct), "prop": n / total})
    p = pd.DataFrame(recs)
    return p.groupby("celltype")["prop"].mean()


def pooled_stat(df, label_col, value_col, fn):
    """Pooled (per-cell) statistic of value_col within each label."""
    g = df.dropna(subset=[value_col]).groupby(label_col, observed=True)[value_col]
    return g.agg(fn), g.size()


def corr_block(merged, xcol, ycol):
    x = merged[xcol].values.astype(float)
    y = merged[ycol].values.astype(float)
    out = {"n": int(len(merged))}
    out["pearson_raw"] = float(pearsonr(x, y)[0])
    out["spearman"] = float(spearmanr(x, y)[0])
    pos = (x > 0) & (y > 0)
    out["pearson_log10"] = float(pearsonr(np.log10(x[pos]), np.log10(y[pos]))[0]) if pos.sum() > 3 else np.nan
    out["n_log10"] = int(pos.sum())
    return out


def main():
    assert HAS_MERFISH_REF, "MERFISH reference not found; cannot build validation data."

    # ---- MERFISH (obs-only, backed) ----
    print("Loading MERFISH cortical cells (manual depth annotation)...")
    mer = load_merfish_cortical()  # cols: donor, subclass, supertype, depth, layer_annotation
    print(f"  {len(mer):,} cells, {mer['donor'].nunique()} donors")

    # supertype -> class map (from MERFISH, since it has both columns per cell)
    sup2sub = (mer[["supertype", "subclass"]].drop_duplicates()
               .set_index("supertype")["subclass"].to_dict())

    def klass_of(ct, level):
        sub = ct if level == "subclass" else sup2sub.get(ct, None)
        return SUBCLASS_TO_CLASS.get(sub, "Unknown")

    # ---- Xenium (obs-only via load_cells, 24 donors, cortical, corr labels) ----
    print("Loading Xenium cortical cells (corr_qc_pass, L1-L6)...")
    sample_ids = sorted(f.replace("_annotated.h5ad", "")
                        for f in os.listdir(H5AD_DIR) if f.endswith("_annotated.h5ad"))
    xen_parts = []
    for sid in sample_ids:
        if sid in EXCLUDE_SAMPLES:
            continue
        d = load_cells(sid, cortical_only=True, qc_mode="corr",
                       extra_obs_columns=["predicted_norm_depth"])
        xen_parts.append(d)
        print(f"  {sid}: {len(d):,} cortical corr-QC cells")
    xen = pd.concat(xen_parts, ignore_index=True)
    print(f"  {len(xen):,} Xenium cells, {xen['sample_id'].nunique()} donors")

    levels = {"subclass": ("subclass", "subclass_label"),
              "supertype": ("supertype", "supertype_label")}
    stats = []

    for level, (mer_lab, xen_lab) in levels.items():
        # ---- proportions ----
        m_prop = mean_prop_across_donors(mer, "donor", mer_lab).rename("merfish_prop")
        x_prop = mean_prop_across_donors(xen, "sample_id", xen_lab).rename("xenium_prop")
        m_n = mer[mer_lab].value_counts().rename("n_merfish_cells")
        x_n = xen[xen_lab].value_counts().rename("n_xenium_cells")
        prop = pd.concat([m_prop, x_prop, m_n, x_n], axis=1).dropna(subset=["merfish_prop", "xenium_prop"])
        prop = prop[(prop.n_merfish_cells >= MIN_CELLS) & (prop.n_xenium_cells >= MIN_CELLS)]
        prop = prop.reset_index().rename(columns={"index": "celltype"})
        prop["klass"] = [klass_of(c, level) for c in prop.celltype]
        prop = prop.sort_values("merfish_prop", ascending=False)
        prop.to_csv(os.path.join(OUT_DIR, f"prop_{level}.csv"), index=False)
        cb = corr_block(prop, "merfish_prop", "xenium_prop")
        stats.append({"panel": f"proportion_{level}", **cb})
        print(f"\n[proportion {level}] n={cb['n']}  Pearson(raw)={cb['pearson_raw']:.3f}  "
              f"Pearson(log10)={cb['pearson_log10']:.3f}  Spearman={cb['spearman']:.3f}")

        # ---- depth ----
        m_d, m_dn = pooled_stat(mer, mer_lab, "depth", "median")
        x_d, x_dn = pooled_stat(xen, xen_lab, "predicted_norm_depth", "median")
        depth = pd.concat([m_d.rename("merfish_depth"), m_dn.rename("n_merfish_cells"),
                           x_d.rename("xenium_depth"), x_dn.rename("n_xenium_cells")], axis=1)
        depth = depth.dropna(subset=["merfish_depth", "xenium_depth"])
        depth = depth[(depth.n_merfish_cells >= MIN_CELLS) & (depth.n_xenium_cells >= MIN_CELLS)]
        depth = depth.reset_index().rename(columns={"index": "celltype"})
        depth["klass"] = [klass_of(c, level) for c in depth.celltype]
        depth = depth.sort_values("merfish_depth")
        depth.to_csv(os.path.join(OUT_DIR, f"depth_{level}.csv"), index=False)
        cb = corr_block(depth, "merfish_depth", "xenium_depth")
        stats.append({"panel": f"depth_{level}", **cb})
        print(f"[depth {level}]      n={cb['n']}  Pearson(raw)={cb['pearson_raw']:.3f}  "
              f"Spearman={cb['spearman']:.3f}")

    sdf = pd.DataFrame(stats)
    sdf.to_csv(os.path.join(OUT_DIR, "concordance_stats.csv"), index=False)
    print(f"\nWrote tables + concordance_stats.csv to {OUT_DIR}")


if __name__ == "__main__":
    main()
